import type { Metadata } from "next";
import "./globals.css";
import { PropsWithChildren } from 'react'
import { EEmailStatus } from '@/types'
import { getEmails } from '@/server-actions'
import { EmailListProvider } from '@/context'
import { SideBar } from './_components'

interface RootLayoutProps extends PropsWithChildren {
  searchParams: Promise<{
    status?: EEmailStatus
  }>
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: RootLayoutProps) {
  const { children, searchParams } = props
  const params = await searchParams
  const status = params?.status ?? EEmailStatus.Active

  const emails = await getEmails(status)

  return (
    <html lang="en">
      <body>
      <EmailListProvider emails={emails}>
        <SideBar>
          {children}
        </SideBar>
      </EmailListProvider>
      </body>
    </html>
  );
}
